import os
from github import Github
from datetime import datetime

def create_pull_request(repo_url: str, file_path: str, fixed_code: str, github_token: str = None):
    # Use provided token or fallback to env var
    token = github_token or os.environ.get("GITHUB_TOKEN")
    if not token:
        raise ValueError("GitHub token not found")

    g = Github(token)

    # repo_url example: https://github.com/user/repo
    repo_name = repo_url.replace("https://github.com/", "").strip("/")
    repo = g.get_repo(repo_name)

    # Create a new branch
    branch_name = f"logsnap-fix-{datetime.now().strftime('%Y%m%d-%H%M%S')}"
    source = repo.get_branch("main") # Assuming main branch
    repo.create_git_ref(ref=f"refs/heads/{branch_name}", sha=source.commit.sha)

    # Get the file to update
    contents = repo.get_contents(file_path, ref=branch_name)

    # Update the file
    repo.update_file(
        path=file_path,
        message="LogSnap: AI-generated fix for error",
        content=fixed_code,
        sha=contents.sha,
        branch=branch_name
    )

    # Create PR
    pr = repo.create_pull(
        title="LogSnap: Auto-fix for logs",
        body="This PR was automatically generated by LogSnap to fix a detected error.",
        head=branch_name,
        base="main"
    )

    return pr.html_url
